---
generic-service:
  nameOverride: hmpps-accredited-programmes-api
  serviceAccountName: hmpps-accredited-programmes-service-account

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-accredited-programmes-api
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-accredited-programmes-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SENTRY_SAMPLE-RATE: 1
    SENTRY_TRACES-SAMPLE-RATE: 0.2
    SPRING_DATASOURCE_URL: "jdbc:postgresql://${DB_HOST}/${DB_NAME}?sslmode=verify-full"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-accredited-programmes-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SENTRY_DSN: "SENTRY_DSN"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PRISON-API_CLIENT-ID: "SYSTEM_CLIENT_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PRISON-API_CLIENT-SECRET: "SYSTEM_CLIENT_SECRET"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PRISONER-SEARCH-API_CLIENT-ID: "SYSTEM_CLIENT_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PRISONER-SEARCH-API_CLIENT-SECRET: "SYSTEM_CLIENT_SECRET"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PRISON-REGISTER-API_CLIENT-ID: "SYSTEM_CLIENT_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PRISON-REGISTER-API_CLIENT-SECRET: "SYSTEM_CLIENT_SECRET"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OASYS-API_CLIENT-ID: "SYSTEM_CLIENT_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OASYS-API_CLIENT-SECRET: "SYSTEM_CLIENT_SECRET"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MANAGE-OFFENCES-API_CLIENT-ID: "SYSTEM_CLIENT_ID"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MANAGE-OFFENCES-API_CLIENT-SECRET: "SYSTEM_CLIENT_SECRET"
    rds-postgresql-instance-output:
      DB_HOST: "rds_instance_endpoint"
      DB_NAME: "database_name"
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"
    sqs-domain-events-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINEVENTSQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-domain-events-dl-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINEVENTSQUEUE_DLQ_NAME: "sqs_queue_name"
generic-prometheus-alerts:
  targetApplication: hmpps-accredited-programmes-api

dataExtractorEnabled: true


