services:
  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    container_name: hmpps-auth
    networks:
      - hmpps
    ports:
      - "9090:8080"
    healthcheck:
      test:
        [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - SPRING_H2_CONSOLE_SETTINGS_WEBALLOWOTHERS=true

  prison-api:
    container_name: prison-api
    depends_on:
      - hmpps-auth
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://hmpps-auth:8080/auth/.well-known/jwks.json
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    image: ghcr.io/ministryofjustice/prison-api:latest
    networks:
      - hmpps
    ports:
      - '9094:8080'

  prison-register-api:
    container_name: prison-register-api
    depends_on:
      - prison-register-db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - OAUTH_ENDPOINT_URL=http://hmpps-auth:8080/auth
      - DATABASE_NAME=prison-register
      - SPRING_DATASOURCE_USERNAME=prison-register
      - SPRING_DATASOURCE_PASSWORD=prison-register
      - SPRING_DATASOURCE_URL=jdbc:postgresql://prison-register-db:5432/postgres
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    image: quay.io/hmpps/prison-register:latest
    networks:
      - hmpps
    ports:
      - '9096:8080'

  prison-register-db:
    container_name: prison-register-db
    environment:
      - POSTGRES_PASSWORD=prison-register
      - POSTGRES_USER=prison-register
      - POSTGRES_DB=prison-register
    image: postgres:15
    networks:
      - hmpps
    ports:
      - '5433:5432'
    restart: always

  postgresql:
    image: postgres
    container_name: postgres
    networks:
      - hmpps
    restart: always
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "--username=admin", "--dbname=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password

  localstack:
    image: localstack/localstack:4
    networks:
      - hmpps
    container_name: hmpps-acp-localstack
    ports:
      - "4566:4566"
      - 8999:8080
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  wiremock:
    image: wiremock/wiremock:2.35.0
    networks:
      - hmpps
    container_name: wiremock
    ports:
      - "9095:8080"
    volumes:
      - ./wiremock:/home/wiremock

  manage-offences-api:
    container_name: manage-offences-api
    depends_on:
      - hmpps-auth
    environment:
      - SERVER_PORT=8080
      - OAUTH_ENDPOINT_URL=http://hmpps-auth:8080/auth
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://hmpps-auth:8080/auth/.well-known/jwks.json
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    image: quay.io/hmpps/hmpps-manage-offences-api:latest
    networks:
      - hmpps
    ports:
      - '9097:8080'

  nomis-user-roles-api:
    container_name: nomis-user-roles-api
    depends_on:
      - hmpps-auth
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://hmpps-auth:8080/auth/.well-known/jwks.json
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    image: quay.io/hmpps/nomis-user-roles-api:latest
    networks:
      - hmpps
    ports:
      - '9102:8080'

  hmpps-accredited-programmes-api:
    image: quay.io/hmpps/hmpps-accredited-programmes-api:latest
    container_name: hmpps-accredited-programmes-api
    networks:
      - hmpps
    ports:
      - "8080:8080"
    healthcheck:
      test:
        [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    depends_on:
      postgresql:
        condition: service_healthy
      hmpps-auth:
        condition: service_healthy

    environment:
      - SPRING_PROFILES_ACTIVE=dev,local,seed
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - SERVICES_PRISONER-SEARCH-API_BASE-URL=http://wiremock:8080
      - SERVICES_PRISON-REGISTER-API_BASE-URL=http://prison-register-api:8080
      - SERVICES_OASYS-API_BASE-URL=http://wiremock:8080
      - SERVICES_MANAGE-OFFENCES-API_BASE-URL=http://wiremock:8080
      - SERVICES_CASE-NOTES-API_BASE-URL=http://wiremock:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin_password

networks:
  hmpps:
