version: "3"
services:
  hmpps-accredited-programmes-api:
    build:
      context: .
    container_name: hmpps-accredited-programmes-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

networks:
  hmpps:
