version: "3"
services:
  database:
    image: "postgis/postgis"
    container_name: accredited-programmes-postgres-dev
    environment:
      - POSTGRES_USER=localdev
      - POSTGRES_PASSWORD=localdev_password
      - POSTGRES_DB=accredited-programmes_localdev
    volumes:
      - database-data-development:/var/lib/postgresql/data/
    ports:
      - "5431:5432"

  hmpps-accredited-programmes-api:
    build:
      context: .
    container_name: hmpps-accredited-programmes-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

volumes:
  database-data-development:

networks:
  hmpps:
