version: "3"
services:
  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    container_name: hmpps-auth
    networks:
      - hmpps
    ports:
      - "9090:8080"
    healthcheck:
      test:
        [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - SPRING_H2_CONSOLE_SETTINGS_WEBALLOWOTHERS=true

  prison-api:
    container_name: prison-api
    depends_on:
      - hmpps-auth
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://hmpps-auth:8080/auth/.well-known/jwks.json
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    image: quay.io/hmpps/prison-api:latest
    networks:
      - hmpps
    ports:
      - '9094:8080'

  prisoner-search:
    image: wiremock/wiremock:2.35.0
    networks:
      - hmpps
    container_name: prisoner-search
    ports:
      - "9095:8080"
    volumes:
      - ./prisoner-search-data:/home/wiremock

  prison-register-api:
    container_name: prison-register-api
    depends_on:
      - prison-register-db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - OAUTH_ENDPOINT_URL=http://hmpps-auth:8080/auth
      - DATABASE_NAME=prison-register
      - SPRING_DATASOURCE_USERNAME=prison-register
      - SPRING_DATASOURCE_PASSWORD=prison-register
      - SPRING_DATASOURCE_URL=jdbc:postgresql://prison-register-db:5432/postgres
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
    image: quay.io/hmpps/prison-register:latest
    networks:
      - hmpps
    ports:
      - '9096:8080'

  prison-register-db:
    container_name: prison-register-db
    environment:
      - POSTGRES_PASSWORD=prison-register
      - POSTGRES_USER=prison-register
      - POSTGRES_DB=prison-register
    image: postgres:15
    networks:
      - hmpps
    ports:
      - '5433:5432'
    restart: always

  postgresql:
    image: postgres
    container_name: postgres
    networks:
      - hmpps
    restart: always
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "--username=admin", "--dbname=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password

  hmpps-accredited-programmes-api:
    image: quay.io/hmpps/hmpps-accredited-programmes-api:latest
    container_name: hmpps-accredited-programmes-api
    networks:
      - hmpps
    ports:
      - "8080:8080"
    healthcheck:
      test:
        [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    depends_on:
      postgresql:
        condition: service_healthy
      hmpps-auth:
        condition: service_healthy

    environment:
      - SPRING_PROFILES_ACTIVE=dev,local,seed
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin_password

networks:
  hmpps:
