#!/usr/bin/env bash

declare -A API_URLS
API_URLS['dev']=https://accredited-programmes-api-dev.hmpps.service.justice.gov.uk
API_URLS['preprod']=https://accredited-programmes-api-preprod.hmpps.service.justice.gov.uk
API_URLS['prod']=https://accredited-programmes-api.hmpps.service.justice.gov.uk

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

. "$DIR/.namespace"
TOKEN=$("$DIR/get-token" -ns ${NS_KEY})
API_URL=${API_URLS[$NS_KEY]}

curl --header "Authorization: Bearer $TOKEN" --header "Accept: application/json" "$API_URL/courses"
