spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin_password

hmpps.sqs:
  provider: localstack
  queues:
    hmppsdomaineventsqueue:
      queueName: hmpps_domain_events_queue
      dlqName: hmpps_domain_events_dlq
      subscribeTopicId: hmppsdomaineventstopic
      subscribeFilter: '{"eventType":[ "prisoner-offender-search.prisoner.updated"] }'
      asyncQueueClient: true

  topics:
    hmppsdomaineventstopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}