oauth:
  client:
    id: hmpps-accredited-programmes-client-1
    secret: clientsecret

hmpps:
  auth:
    url: http://localhost:9090/auth

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin_password

services:
  prison-api:
    base-url: http://localhost:9094