openapi: 3.0.1
info:
  title: Accredited Programmes API
  version: 1.0.0
servers:
  - url: /
paths:
  /programmes:
    get:
      tags:
        - Programmes
      summary: List all accredited programmes
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Programme'
components:
  schemas:
    Programme:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Thinking skills programme
        programmeType:
          type: string
          example: TypeA
        description:
          type: string
          example: Thinking Skills Programme (TSP) description
        programmePrerequisites:
          type: array
          items:
            $ref: '#/components/schemas/ProgrammePrerequisite'
    ProgrammePrerequisite:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
      example:
        - key: gender
          value: female
        - key: risk score
          value: 'ORGS: 50+'
        - key: offence type
          value: some offence here
