openapi: 3.0.1
info:
  title: Accredited Programmes API
  version: 1.0.0
servers:
  - url: /
security:
  - bearerAuth: [ ]
paths:
  /subject-access-request:
    get:
      operationId: subjectAccessRequestGet
      summary: API call to retrieve SAR information about a person
      tags:
        - Subject Access Request
      description: |
        Either NOMIS Prison Number (PRN) must be provided as part of the request.
        * If the product uses the identifier type transmitted in the request, it can respond with its data and HTTP code 200.
        * If the product uses the identifier type transmitted in the request but has no data to respond with, it should respond with HTTP code 204
        * If the product does not use the identifier type transmitted in the request, it should respond with HTTP code 209.
      parameters:
        - name: prn
          in: query
          description: prison number
          required: false
          schema:
            type: string
        - name: fromDate
          in: query
          description: from date
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          description: to date
          schema:
            type: string
            format: date
      responses:
        '200':
          description: the sar content
          content:
            application/json:
              schema:
                type: object
        '204':
          description: Request successfully processed - no content found
        '209':
          description: Subject Identifier is not recognised by this service

  /user/me/caseload:
    get:
      summary: Get list of caseloads for current user
      operationId: getCurrentUserCaseloads
      parameters:
        - name: allCaseloads
          in: query
          description: Flag to indicate whether to retrieve all caseloads or not. Set to false by default
          schema:
            type: boolean
            default: false
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CaseLoad'
                type: array
          description: Retrieves the caseloads associated with the authenticated user.
        "401":
          description: Unauthorised. The request was unauthorised.
        "403":
          description: Forbidden.  The client is not authorised to access.
      tags:
        - User
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 404
        errorCode:
          type: integer
        userMessage:
          type: string
          example: "Not found"
        developerMessage:
          type: string
        moreInfo:
          type: string
      required:
        - status

    CaseLoad:
      type: object
      properties:
        caseLoadId:
          type: string
          nullable: true
          description: The unique identifier of the caseload.
        description:
          type: string
          nullable: true
          description: The description of the caseload.
        type:
          type: string
          nullable: true
          description: The type of the caseload.
        caseloadFunction:
          type: string
          nullable: true
          description: The function of the caseload.
        currentlyActive:
          type: boolean
          nullable: true
          description: Indicates whether the caseload is currently active or not.


