openapi: 3.0.1
info:
  title: Accredited Programs API
  version: 1.0.0
servers:
  - url: /
paths:
  /hello:
    get:
      tags:
        - Test
      summary: Test endpoint
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: string
