openapi: 3.0.1
info:
  title: Accredited Programmes API
  version: 1.0.0
servers:
  - url: /
security:
  - bearerAuth: [ ]
paths:
  /dummy:
    get:
      operationId: dummy
      summary: DummyAPI
      responses:
        '200':
          description: dummyresponse
          content:
            application/json:
              schema:
                type: object


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT






