package uk.gov.justice.digital.hmpps.hmppsaccreditedprogrammesapi.service.type

enum class ReferralStatus {
  ASSESSMENT_STARTED,
  ON_PROGRAMME,
  SUITABLE_NOT_READY,
  PROGRAMME_COMPLETE,
  NOT_ELIGIBLE,
  WITHDRAWN,
  NOT_SUITABLE,
  REFERRAL_SUBMITTED,
  DESELECTED,
  REFERRAL_STARTED,
  ASSESSED_SUITABLE,
  AWAITING_ASSESSMENT,
  ON_HOLD_REFERRAL_SUBMITTED,
  ON_HOLD_ASSESSMENT_STARTED,
  ON_HOLD_AWAITING_ASSESSMENT,
  MOVED_TO_BUILDING_CHOICES,
}
