---
# Per environment values which override defaults in hmpps-accredited-programmes-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: accredited-programmes-api-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-accredited-programmes-api-dev-cert

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    SERVICES_PRISON-API_BASE-URL: https://prison-api-dev.prison.service.justice.gov.uk
    SERVICES_PRISONER-SEARCH-API_BASE-URL: https://prisoner-search-dev.prison.service.justice.gov.uk
    SERVICES_PRISON-REGISTER-API_BASE-URL: https://prison-register-dev.hmpps.service.justice.gov.uk
    SERVICES_OASYS-API_BASE-URL: https://accredited-programmes-and-oasys-dev.hmpps.service.justice.gov.uk
    SERVICES_MANAGE-OFFENCES-API_BASE-URL: https://manage-offences-api-dev.hmpps.service.justice.gov.uk
    SERVICES_CASE-NOTES-API_BASE-URL: https://dev.offender-case-notes.service.justice.gov.uk
    SERVICES_ALLOCATION-MANAGER-API_BASE-URL: https://dev.moic.service.justice.gov.uk
    SERVICES_NOMIS-USER-ROLES-API_BASE-URL: https://nomis-user-roles-api-dev.prison.service.justice.gov.uk
    SERVICES_PRISONER-ALERTS-API_BASE-URL: https://alerts-api-dev.hmpps.service.justice.gov.uk
    SENTRY_ENVIRONMENT: dev
    HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: "Digital-Prison-Services-dev-hmpps_audit_queue"
    LOGGING_LEVEL_UK_GOV_JUSTICE_DIGITAL_HMPPS_HMPPSACCREDITEDPROGRAMMESAPI_SERVICE: DEBUG
    FEATURESWITCH_CASE-NOTES-ENABLED: true


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

elasticCacheAlertsClusterIds:
  - "cp-77908e27cb279610-001"
  - "cp-77908e27cb279610-002"

rdsAlertsDatabases:
  "db8ec03e49ab6abf06": "Accredited Programmes API Database"

dataExtractorEnabled: true
dataRefreshEnabled: false


spring:
  application:
    environment: dev