---
# Per environment values which override defaults in hmpps-accredited-programmes-api/values.yaml

generic-service:
  ingress:
    host: accredited-programmes-api-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-accredited-programmes-api-preprod-cert

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    SERVICES_PRISON-API_BASE-URL: https://api-preprod.prison.service.justice.gov.uk
    SERVICES_PRISONER-SEARCH-API_BASE-URL: https://prisoner-search-preprod.prison.service.justice.gov.uk
    SERVICES_PRISON-REGISTER-API_BASE-URL: https://prison-register-preprod.hmpps.service.justice.gov.uk
    SERVICES_OASYS-API_BASE-URL: https://accredited-programmes-and-oasys-preprod.hmpps.service.justice.gov.uk
    SERVICES_ARNS-API_BASE-URL: https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk/
    SENTRY_ENVIRONMENT: preprod
    HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: "Digital-Prison-Services-preprod-hmpps_audit_queue"

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
