---
# Per environment values which override defaults in hmpps-accredited-programmes-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: accredited-programmes-api-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-accredited-programmes-api-dev-cert
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine DetectionOnly
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=2"

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    SERVICES_PRISON-API_BASE-URL: https://prison-api-dev.prison.service.justice.gov.uk
    SERVICES_PRISONER-SEARCH-API_BASE-URL: https://prisoner-search-dev.prison.service.justice.gov.uk
    SERVICES_PRISON-REGISTER-API_BASE-URL: https://prison-register-dev.hmpps.service.justice.gov.uk
    SERVICES_OASYS-API_BASE-URL: https://accredited-programmes-and-oasys-dev.hmpps.service.justice.gov.uk
    SERVICES_ARNS-API_BASE-URL: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk
    SENTRY_ENVIRONMENT: dev
    HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME: "Digital-Prison-Services-dev-hmpps_audit_queue"
    LOGGING_LEVEL_UK_GOV_JUSTICE_DIGITAL_HMPPS_HMPPSACCREDITEDPROGRAMMESAPI_SERVICE: DEBUG

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

elasticCacheAlertsClusterIds:
  - "cp-77908e27cb279610-001"
  - "cp-77908e27cb279610-002"

rdsAlertsDatabases:
  "db8ec03e49ab6abf06": "Accredited Programmes API Database"
