ALTER TABLE referral_status_reason
    ADD COLUMN DESELECT_OPEN BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE REFERRAL_STATUS_REASON set DESELECT_OPEN = false where CODE = 'D_DEATH';
UPDATE REFERRAL_STATUS_REASON set DESELECT_OPEN = false where CODE = 'D_NOT_AVAILABLE';
UPDATE REFERRAL_STATUS_REASON set DESELECT_OPEN = false where CODE = 'D_DEPORTED';
UPDATE REFERRAL_STATUS_REASON set DESELECT_OPEN = false where CODE = 'D_RELEASED_PAROLE';
UPDATE REFERRAL_STATUS_REASON set DESELECT_OPEN = false where CODE = 'D_SENTENCE_ENDED';