ALTER TABLE course
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE person
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE offering
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE referral
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE referral_status_history
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
